apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::326480123667:role/eksctl-eksworkshop-eksctl-nodegro-NodeInstanceRole-VGUF3OIJLYRJ
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::326480123667:role/KarpenterNodeRole-eksworkshop-eksctl
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::326480123667:user/rbac-user
      username: rbac-user
